image: centos:7

before_script:
    - sed -i 's/keepcache=0/keepcache=1/g' /etc/yum.conf
    - echo "[ -f /etc/yum/pluginconf.d/ovl.conf ] && sed -i -e 's/1/0/g' /etc/yum/pluginconf.d/ovl.conf" | bash
    - yum -y upgrade
    - yum -y install centos-release-scl epel-release
    - yum -y install git make cmake3 boost-devel boost-static curl
        rapidjson-devel glibc-devel openssl-devel devtoolset-3-{gcc,gcc-c++}
        http://192.168.13.121/repo/3rd_party/asn1c-0.9.29-1.el7.centos.x86_64.rpm
    - curl -k https://ca.svc/ca.cer -o /usr/share/pki/ca-trust-source/anchors/svyazcom-ca.cer && update-ca-trust check && update-ca-trust enable

cache:
    paths:
        - build/
        - /var/cache/yum/

stages:
    - build

build_job:
    stage: build
    variables:
        GIT_SUBMODULE_STRATEGY: normal
    script:
        - rm -rf build
        - mkdir -p build
        - cd build
        - echo 'cmake3 .. -DENABLE_EXAMPLES=1' | scl enable devtoolset-3 bash
        - make -j8
    only:
        - master
        - devel
